/**
 * Quiz Page
 * ---------
 * Interactive quiz experience powered by BridgeBot.
 *
 * Responsibilities:
 * - Start and manage a quiz session
 * - Display questions generated by the AI
 * - Accept user answers and submit them for evaluation
 * - Show feedback, explanation, and difficulty level
 *
 * Dark mode design goals:
 * - Calm, distraction-free learning environment
 * - Soft background and surfaces
 * - Reduced contrast for long reading sessions
 */

import { useState, useRef, useEffect } from "react";
import ChatPanel from "../components/chatBot/ChatPanel";
import QuestionsCard from "../components/common/QuestionsCard";
import InputField from "../components/common/InputField";
import PrimaryButton from "../components/common/PrimaryButton";

const Quiz = () => {
  const chatRef = useRef(null);

  const [question, setQuestion] = useState("");
  const [answer, setAnswer] = useState("");
  const [feedback, setFeedback] = useState(null);
  const [explanation, setExplanation] = useState("");
  const [difficulty, setDifficulty] = useState("easy");
  const [isThinking, setIsThinking] = useState(false);

  useEffect(() => {
    const startQuiz = async () => {
      const savedSession = localStorage.getItem("bridgebot_quiz_current");

      if (savedSession) {
        const data = JSON.parse(savedSession);
        handleQuizEvent(data);
        return;
      }

      await new Promise((resolve) => setTimeout(resolve, 500));
      if (chatRef.current) {
        setIsThinking(true);
        chatRef.current.submitQuizAnswer("START_QUIZ");
      }
    };

    startQuiz();
  }, []);

  const handleQuizEvent = (data) => {
    setIsThinking(false);
    setQuestion(data.question);
    setFeedback(data.isCorrect);
    setExplanation(data.explanation);
    setDifficulty(data.difficulty);

    localStorage.setItem("bridgebot_quiz_current", JSON.stringify(data));
  };

  const submitAnswer = () => {
    if (!question) return;
    if (!answer.trim()) return;
    if (isThinking) return;

    setIsThinking(true);
    setFeedback(null);

    chatRef.current.submitQuizAnswer(answer);
    setAnswer("");
  };

  return (
    <div
      className="p-6 max-w-xl mx-auto relative
                    bg-transparent dark:bg-[#0f172a] min-h-screen"
    >
      <h1
        className="text-3xl font-bold mb-6 text-center
                     text-gray-900 dark:text-slate-200"
      >
        Quiz - let’s test you
      </h1>

      {isThinking && !question && (
        <div
          className="text-center p-10 animate-pulse
                        text-blue-500 dark:text-blue-400"
        >
          BridgeBot is preparing your first question...
        </div>
      )}

      {question && (
        <QuestionsCard
          questionNo={feedback === null ? "Current" : "Next"}
          question={question}
        />
      )}

      <div className="mt-6">
        <InputField
          label="Type your answer"
          value={answer}
          onChange={(e) => setAnswer(e.target.value)}
          placeholder="Write your answer here"
          onKeyDown={(e) => e.key === "Enter" && submitAnswer()}
        />

        <div className="mt-4">
          <PrimaryButton
            label={isThinking ? "Thinking..." : "Submit answer"}
            onClick={submitAnswer}
            disabled={isThinking || !answer.trim()}
          />
        </div>
      </div>

      {!question && !isThinking && (
        <div
          className="text-center text-sm mt-6
                        text-gray-400 dark:text-slate-400"
        >
          Waiting for the next question...
        </div>
      )}

      {feedback !== null && !isThinking && (
        <div
          className={`mt-6 p-4 rounded-lg border transition
            ${
              feedback
                ? "bg-green-50 border-green-200 text-green-800 dark:bg-green-900/20 dark:border-green-800 dark:text-green-200"
                : "bg-red-50 border-red-200 text-red-800 dark:bg-red-900/20 dark:border-red-800 dark:text-red-200"
            }
          `}
        >
          <p className="font-semibold">
            {feedback ? "Correct answer" : "Incorrect answer"}
          </p>

          <p className="text-sm mt-2 opacity-90">{explanation}</p>

          <p className="text-xs mt-3 opacity-70 uppercase tracking-wide">
            Difficulty: {difficulty}
          </p>
        </div>
      )}

      {/* Hidden AI engine */}
      <ChatPanel
        ref={chatRef}
        quizMode={true}
        pageContext="quiz"
        onQuizEvent={handleQuizEvent}
      />
    </div>
  );
};

export default Quiz;
